print ('\nDi cosa vuoi calcolare la probabilità?')
variabili = print ('mercato azionario')
qualcosa = input()
if qualcosa == 'mercato azionario' :
    print ('\ndigita valuta')
    valuta = input()
else :
    print ('sium')
print ('\ndigita il valore di apertura e chiusura degli ultimi 5 giorni')   
apertura_uno = input('apertura 1 ')
apertura_due = input('apertura 2 ')
apertura_tre = input('apertura 3 ')
apertura_quattro = input('apertura 4 ')
apertura_cinque = input('apertura 5 ')
chiusura_uno = input('chiusura 1 ')
chiusura_due = input('chiusura 2 ')
chiusura_tre = input('chiusura 3 ')
chiusura_quattro = input('chiusua 4 ')
chiusura_cinque = input('chiusura 5 ')